name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy-to-scratch-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce CLI with NPM
        run: |
          npm install @salesforce/cli --global

      - name: Authorize with the dev hub
        run: |
          echo "${{ secrets.SFDX_AUTH_URL_DEVHUB }}" | sf org login sfdx-url --alias DevHub --set-default-dev-hub --sfdx-url-stdin > /dev/null 2>&1
          echo "✓ Successfully authenticated with Dev Hub"

      - name: Create scratch org
        run: |
          sf org create scratch --definition-file config/project-scratch-def.json --alias ScratchOrg --wait 30 --duration-days 1 --set-default > /dev/null 2>&1
          echo "✓ Successfully created scratch org"

      - name: Push source
        run: sf project deploy start --target-org ScratchOrg --wait 30

      - name: Run tests
        run: sf apex run test --target-org ScratchOrg --code-coverage --result-format human --output-dir ./tests/apex --test-level RunLocalTests --wait 30

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: beyond-the-cloud-dev/dml-lib
          flags: Apex

      - name: Delete scratch org
        if: always()
        run: |
          sf org delete scratch --target-org ScratchOrg --no-prompt > /dev/null 2>&1
          echo "✓ Scratch org cleanup completed"
